// Pour les menus déroulants des champs du formulaire d'inscription

export const COUNTRIES = [
    { code: "FR", name: "France" },
    { code: "BE", name: "Belgique" },
    { code: "CH", name: "Suisse" },
    { code: "CA", name: "Canada" },
    { code: "LU", name: "Luxembourg" },
    { code: "MC", name: "Monaco" },
    { code: "AF", name: "Afghanistan" },
    { code: "ZA", name: "Afrique du Sud" },
    { code: "AL", name: "Albanie" },
    { code: "DZ", name: "Algérie" },
    { code: "DE", name: "Allemagne" },
    { code: "AD", name: "Andorre" },
    { code: "AO", name: "Angola" },
    { code: "AG", name: "Antigua-et-Barbuda" },
    { code: "SA", name: "Arabie Saoudite" },
    { code: "AR", name: "Argentine" },
    { code: "AM", name: "Arménie" },
    { code: "AU", name: "Australie" },
    { code: "AT", name: "Autriche" },
    { code: "AZ", name: "Azerbaïdjan" },
    { code: "BS", name: "Bahamas" },
    { code: "BH", name: "Bahreïn" },
    { code: "BD", name: "Bangladesh" },
    { code: "BB", name: "Barbade" },
    { code: "BZ", name: "Belize" },
    { code: "BJ", name: "Bénin" },
    { code: "BT", name: "Bhoutan" },
    { code: "BY", name: "Biélorussie" },
    { code: "MM", name: "Birmanie" },
    { code: "BO", name: "Bolivie" },
    { code: "BA", name: "Bosnie-Herzégovine" },
    { code: "BW", name: "Botswana" },
    { code: "BR", name: "Brésil" },
    { code: "BN", name: "Brunei" },
    { code: "BG", name: "Bulgarie" },
    { code: "BF", name: "Burkina Faso" },
    { code: "BI", name: "Burundi" },
    { code: "KH", name: "Cambodge" },
    { code: "CM", name: "Cameroun" },
    { code: "CV", name: "Cap-Vert" },
    { code: "CL", name: "Chili" },
    { code: "CN", name: "Chine" },
    { code: "CY", name: "Chypre" },
    { code: "CO", name: "Colombie" },
    { code: "KM", name: "Comores" },
    { code: "CG", name: "Congo-Brazzaville" },
    { code: "CD", name: "Congo-Kinshasa" },
    { code: "KP", name: "Corée du Nord" },
    { code: "KR", name: "Corée du Sud" },
    { code: "CR", name: "Costa Rica" },
    { code: "CI", name: "Côte d'Ivoire" },
    { code: "HR", name: "Croatie" },
    { code: "CU", name: "Cuba" },
    { code: "DK", name: "Danemark" },
    { code: "DJ", name: "Djibouti" },
    { code: "DM", name: "Dominique" },
    { code: "EG", name: "Égypte" },
    { code: "AE", name: "Émirats arabes unis" },
    { code: "EC", name: "Équateur" },
    { code: "ER", name: "Érythrée" },
    { code: "ES", name: "Espagne" },
    { code: "EE", name: "Estonie" },
    { code: "SZ", name: "Eswatini" },
    { code: "US", name: "États-Unis" },
    { code: "ET", name: "Éthiopie" },
    { code: "FJ", name: "Fidji" },
    { code: "FI", name: "Finlande" },
    { code: "GA", name: "Gabon" },
    { code: "GM", name: "Gambie" },
    { code: "GE", name: "Géorgie" },
    { code: "GH", name: "Ghana" },
    { code: "GR", name: "Grèce" },
    { code: "GD", name: "Grenade" },
    { code: "GT", name: "Guatemala" },
    { code: "GN", name: "Guinée" },
    { code: "GW", name: "Guinée-Bissau" },
    { code: "GQ", name: "Guinée équatoriale" },
    { code: "GY", name: "Guyana" },
    { code: "HT", name: "Haïti" },
    { code: "HN", name: "Honduras" },
    { code: "HU", name: "Hongrie" },
    { code: "IN", name: "Inde" },
    { code: "ID", name: "Indonésie" },
    { code: "IQ", name: "Irak" },
    { code: "IR", name: "Iran" },
    { code: "IE", name: "Irlande" },
    { code: "IS", name: "Islande" },
    { code: "IL", name: "Israël" },
    { code: "IT", name: "Italie" },
    { code: "JM", name: "Jamaïque" },
    { code: "JP", name: "Japon" },
    { code: "JO", name: "Jordanie" },
    { code: "KZ", name: "Kazakhstan" },
    { code: "KE", name: "Kenya" },
    { code: "KG", name: "Kirghizistan" },
    { code: "KI", name: "Kiribati" },
    { code: "KW", name: "Koweït" },
    { code: "LA", name: "Laos" },
    { code: "LS", name: "Lesotho" },
    { code: "LV", name: "Lettonie" },
    { code: "LB", name: "Liban" },
    { code: "LR", name: "Liberia" },
    { code: "LY", name: "Libye" },
    { code: "LI", name: "Liechtenstein" },
    { code: "LT", name: "Lituanie" },
    { code: "MK", name: "Macédoine du Nord" },
    { code: "MG", name: "Madagascar" },
    { code: "MY", name: "Malaisie" },
    { code: "MW", name: "Malawi" },
    { code: "MV", name: "Maldives" },
    { code: "ML", name: "Mali" },
    { code: "MT", name: "Malte" },
    { code: "MA", name: "Maroc" },
    { code: "MH", name: "Marshall" },
    { code: "MU", name: "Maurice" },
    { code: "MR", name: "Mauritanie" },
    { code: "MX", name: "Mexique" },
    { code: "FM", name: "Micronésie" },
    { code: "MD", name: "Moldavie" },
    { code: "MN", name: "Mongolie" },
    { code: "ME", name: "Monténégro" },
    { code: "MZ", name: "Mozambique" },
    { code: "NA", name: "Namibie" },
    { code: "NR", name: "Nauru" },
    { code: "NP", name: "Népal" },
    { code: "NI", name: "Nicaragua" },
    { code: "NE", name: "Niger" },
    { code: "NG", name: "Nigeria" },
    { code: "NO", name: "Norvège" },
    { code: "NZ", name: "Nouvelle-Zélande" },
    { code: "OM", name: "Oman" },
    { code: "UG", name: "Ouganda" },
    { code: "UZ", name: "Ouzbékistan" },
    { code: "PK", name: "Pakistan" },
    { code: "PW", name: "Palaos" },
    { code: "PA", name: "Panama" },
    { code: "PG", name: "Papouasie-Nouvelle-Guinée" },
    { code: "PY", name: "Paraguay" },
    { code: "NL", name: "Pays-Bas" },
    { code: "PE", name: "Pérou" },
    { code: "PH", name: "Philippines" },
    { code: "PL", name: "Pologne" },
    { code: "PT", name: "Portugal" },
    { code: "QA", name: "Qatar" },
    { code: "CF", name: "République centrafricaine" },
    { code: "DO", name: "République dominicaine" },
    { code: "CZ", name: "République tchèque" },
    { code: "RO", name: "Roumanie" },
    { code: "GB", name: "Royaume-Uni" },
    { code: "RU", name: "Russie" },
    { code: "RW", name: "Rwanda" },
    { code: "KN", name: "Saint-Christophe-et-Niévès" },
    { code: "SM", name: "Saint-Marin" },
    { code: "VC", name: "Saint-Vincent-et-les-Grenadines" },
    { code: "LC", name: "Sainte-Lucie" },
    { code: "SB", name: "Salomon" },
    { code: "SV", name: "Salvador" },
    { code: "WS", name: "Samoa" },
    { code: "ST", name: "Sao Tomé-et-Principe" },
    { code: "SN", name: "Sénégal" },
    { code: "RS", name: "Serbie" },
    { code: "SC", name: "Seychelles" },
    { code: "SL", name: "Sierra Leone" },
    { code: "SG", name: "Singapour" },
    { code: "SK", name: "Slovaquie" },
    { code: "SI", name: "Slovénie" },
    { code: "SO", name: "Somalie" },
    { code: "SD", name: "Soudan" },
    { code: "SS", name: "Soudan du Sud" },
    { code: "LK", name: "Sri Lanka" },
    { code: "SE", name: "Suède" },
    { code: "SR", name: "Suriname" },
    { code: "SY", name: "Syrie" },
    { code: "TJ", name: "Tadjikistan" },
    { code: "TZ", name: "Tanzanie" },
    { code: "TD", name: "Tchad" },
    { code: "TH", name: "Thaïlande" },
    { code: "TL", name: "Timor oriental" },
    { code: "TG", name: "Togo" },
    { code: "TO", name: "Tonga" },
    { code: "TT", name: "Trinité-et-Tobago" },
    { code: "TN", name: "Tunisie" },
    { code: "TM", name: "Turkménistan" },
    { code: "TR", name: "Turquie" },
    { code: "TV", name: "Tuvalu" },
    { code: "UA", name: "Ukraine" },
    { code: "UY", name: "Uruguay" },
    { code: "VU", name: "Vanuatu" },
    { code: "VE", name: "Venezuela" },
    { code: "VN", name: "Vietnam" },
    { code: "YE", name: "Yémen" },
    { code: "ZM", name: "Zambie" },
    { code: "ZW", name: "Zimbabwe" }
];

export const DEPARTMENTS = [
    { code: "01", name: "01 - Ain" },
    { code: "02", name: "02 - Aisne" },
    { code: "03", name: "03 - Allier" },
    { code: "04", name: "04 - Alpes-de-Haute-Provence" },
    { code: "05", name: "05 - Hautes-Alpes" },
    { code: "06", name: "06 - Alpes-Maritimes" },
    { code: "07", name: "07 - Ardèche" },
    { code: "08", name: "08 - Ardennes" },
    { code: "09", name: "09 - Ariège" },
    { code: "10", name: "10 - Aube" },
    { code: "11", name: "11 - Aude" },
    { code: "12", name: "12 - Aveyron" },
    { code: "13", name: "13 - Bouches-du-Rhône" },
    { code: "14", name: "14 - Calvados" },
    { code: "15", name: "15 - Cantal" },
    { code: "16", name: "16 - Charente" },
    { code: "17", name: "17 - Charente-Maritime" },
    { code: "18", name: "18 - Cher" },
    { code: "19", name: "19 - Corrèze" },
    { code: "2A", name: "2A - Corse-du-Sud" },
    { code: "2B", name: "2B - Haute-Corse" },
    { code: "21", name: "21 - Côte-d'Or" },
    { code: "22", name: "22 - Côtes-d'Armor" },
    { code: "23", name: "23 - Creuse" },
    { code: "24", name: "24 - Dordogne" },
    { code: "25", name: "25 - Doubs" },
    { code: "26", name: "26 - Drôme" },
    { code: "27", name: "27 - Eure" },
    { code: "28", name: "28 - Eure-et-Loir" },
    { code: "29", name: "29 - Finistère" },
    { code: "30", name: "30 - Gard" },
    { code: "31", name: "31 - Haute-Garonne" },
    { code: "32", name: "32 - Gers" },
    { code: "33", name: "33 - Gironde" },
    { code: "34", name: "34 - Hérault" },
    { code: "35", name: "35 - Ille-et-Vilaine" },
    { code: "36", name: "36 - Indre" },
    { code: "37", name: "37 - Indre-et-Loire" },
    { code: "38", name: "38 - Isère" },
    { code: "39", name: "39 - Jura" },
    { code: "40", name: "40 - Landes" },
    { code: "41", name: "41 - Loir-et-Cher" },
    { code: "42", name: "42 - Loire" },
    { code: "43", name: "43 - Haute-Loire" },
    { code: "44", name: "44 - Loire-Atlantique" },
    { code: "45", name: "45 - Loiret" },
    { code: "46", name: "46 - Lot" },
    { code: "47", name: "47 - Lot-et-Garonne" },
    { code: "48", name: "48 - Lozère" },
    { code: "49", name: "49 - Maine-et-Loire" },
    { code: "50", name: "50 - Manche" },
    { code: "51", name: "51 - Marne" },
    { code: "52", name: "52 - Haute-Marne" },
    { code: "53", name: "53 - Mayenne" },
    { code: "54", name: "54 - Meurthe-et-Moselle" },
    { code: "55", name: "55 - Meuse" },
    { code: "56", name: "56 - Morbihan" },
    { code: "57", name: "57 - Moselle" },
    { code: "58", name: "58 - Nièvre" },
    { code: "59", name: "59 - Nord" },
    { code: "60", name: "60 - Oise" },
    { code: "61", name: "61 - Orne" },
    { code: "62", name: "62 - Pas-de-Calais" },
    { code: "63", name: "63 - Puy-de-Dôme" },
    { code: "64", name: "64 - Pyrénées-Atlantiques" },
    { code: "65", name: "65 - Hautes-Pyrénées" },
    { code: "66", name: "66 - Pyrénées-Orientales" },
    { code: "67", name: "67 - Bas-Rhin" },
    { code: "68", name: "68 - Haut-Rhin" },
    { code: "69", name: "69 - Rhône" },
    { code: "70", name: "70 - Haute-Saône" },
    { code: "71", name: "71 - Saône-et-Loire" },
    { code: "72", name: "72 - Sarthe" },
    { code: "73", name: "73 - Savoie" },
    { code: "74", name: "74 - Haute-Savoie" },
    { code: "75", name: "75 - Paris" },
    { code: "76", name: "76 - Seine-Maritime" },
    { code: "77", name: "77 - Seine-et-Marne" },
    { code: "78", name: "78 - Yvelines" },
    { code: "79", name: "79 - Deux-Sèvres" },
    { code: "80", name: "80 - Somme" },
    { code: "81", name: "81 - Tarn" },
    { code: "82", name: "82 - Tarn-et-Garonne" },
    { code: "83", name: "83 - Var" },
    { code: "84", name: "84 - Vaucluse" },
    { code: "85", name: "85 - Vendée" },
    { code: "86", name: "86 - Vienne" },
    { code: "87", name: "87 - Haute-Vienne" },
    { code: "88", name: "88 - Vosges" },
    { code: "89", name: "89 - Yonne" },
    { code: "90", name: "90 - Territoire de Belfort" },
    { code: "91", name: "91 - Essonne" },
    { code: "92", name: "92 - Hauts-de-Seine" },
    { code: "93", name: "93 - Seine-Saint-Denis" },
    { code: "94", name: "94 - Val-de-Marne" },
    { code: "95", name: "95 - Val-d'Oise" },
    { code: "971", name: "971 - Guadeloupe" },
    { code: "972", name: "972 - Martinique" },
    { code: "973", name: "973 - Guyane" },
    { code: "974", name: "974 - La Réunion" },
    { code: "976", name: "976 - Mayotte" },
];