security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        # On dit à Symfony d'utiliser ton entité Utilisateur
        app_user_provider:
            entity:
                class: App\Entity\Utilisateur
                property: email

    firewalls:
        dev:
            pattern: ^/(_profiler|_wdt|assets|build)/
            security: false
        main:
            lazy: true
            provider: app_user_provider
            
            # Active le login JSON (pratique pour Next.js/API Platform)
            json_login:
                check_path: api_login
                username_path: email
                password_path: password

            # Active la déconnexion
            logout:
                path: app_logout

    access_control:
        # La borne doit pouvoir inscrire des visiteurs sans être connectée
        - { path: ^/api/visiteurs, methods: [POST] }
        - { path: ^/api/register-visitor, methods: [POST] }

        # Seuls les étudiants/admin voient la liste des visites
        - { path: ^/api/visites, roles: [ROLE_ETUDIANT, ROLE_ADMIN] }
        
        # Le reste de l'API nécessite d'être connecté
        - { path: ^/api, roles: IS_AUTHENTICATED_FULLY }