vich_uploader:
    db_driver: orm 

    mappings:
        departement_pdfs:
            uri_prefix: /plans
            upload_destination: '%kernel.project_dir%/public/plans'
            namer: App\Naming\PdfNamer 